<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root [   <!ELEMENT root ANY>   <!ELEMENT item ANY>   <!ATTLIST item ID ID #REQUIRED>   <!ATTLIST item Explanation CDATA #IMPLIED>]><root>
	<item ID="APPPATH">C:\Users\Administrator\git\wei1224hf-myappcc\WebContent\</item>
	<item ID="IL8N" Explanation="Language must fit the folder name in WebContent/language/">zh-cn</item>
	<item ID="DB_TYPE">postgresql</item>	
	<item ID="DB_HOST" Explanation="IN JAVA , set NULL ; in php or .net need this">NULL</item>
	<item ID="DB_NAME">NULL</item>
	<item ID="DB_UNM">NULL</item>
	<item ID="DB_PWD">NULL</item>
	<item ID="DB_URL" Explanation="only in java need this"><![CDATA[jdbc:postgresql://localhost:5432/myapp?user=postgres&password=postgres]]></item>
	<item ID="MODE" Explanation="System may run togerther with other system , such as DiscuzX , phpWind and so on">independent</item>
	<item ID="ZONE" Explanation="see GB2260 , China-Standard">330281</item>
	<item ID="ZONE4">3302</item>
	<item ID="ZONE6">330281</item>
	<item ID="ZONE8">33028101</item>
	<item ID="reLoad">donothing</item>
</root>